# Generated by Django 5.0.3 on 2024-03-27 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bcart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oncart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carts_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Oncart',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcart.product')),
                ('oncart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncart.oncart')),
            ],
            options={
                'db_table': 'CartItem',
            },
        ),
    ]
